CREATE DOMAIN IF NOT EXISTS jsonb AS json;
CREATE TABLE IF NOT EXISTS org (
  org_code varchar(30) PRIMARY KEY, org_name varchar(200) NOT NULL, org_type varchar(30) NOT NULL CHECK (org_type IN ('UNIVERSITY','GRADUATE_SCHOOL','COLLEGE','DEPARTMENT','OFFICE')), use_yn char(1) NOT NULL CHECK (use_yn IN ('Y','N')), created_at timestamp NOT NULL, updated_at timestamp NOT NULL
);
CREATE TABLE IF NOT EXISTS korus_personnel_snapshot (
  person_id varchar(50) PRIMARY KEY, name varchar(100) NOT NULL, org_code varchar(30) REFERENCES org(org_code), position_name varchar(100), rank_name varchar(100), employment_status varchar(30), retired_at date, last_synced_at timestamp NOT NULL, created_at timestamp NOT NULL, updated_at timestamp NOT NULL
);
CREATE TABLE IF NOT EXISTS app_user (
  user_id varchar(50) PRIMARY KEY, korus_person_id varchar(50) REFERENCES korus_personnel_snapshot(person_id), password_hash varchar(255) NOT NULL, use_yn char(1) NOT NULL CHECK (use_yn IN ('Y','N')), status varchar(20) NOT NULL CHECK (status IN ('ACTIVE','INACTIVE','REVOKED')), created_at timestamp NOT NULL, updated_at timestamp NOT NULL
);
CREATE TABLE IF NOT EXISTS org_relation (
  relation_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, org_code varchar(30) NOT NULL REFERENCES org(org_code), parent_org_code varchar(30) REFERENCES org(org_code), valid_from date NOT NULL, valid_to date, change_reason varchar(500), created_at timestamp NOT NULL, updated_at timestamp NOT NULL, CHECK (valid_to IS NULL OR valid_to >= valid_from)
);
CREATE TABLE IF NOT EXISTS org_user_position (
  mapping_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, person_id varchar(50) NOT NULL REFERENCES korus_personnel_snapshot(person_id), org_code varchar(30) NOT NULL REFERENCES org(org_code), position_name varchar(100), created_at timestamp NOT NULL, updated_at timestamp NOT NULL
);
CREATE TABLE IF NOT EXISTS role (
  role_code varchar(3) PRIMARY KEY CHECK (role_code IN ('R01','R02','R03','R04','R05','R06','R07','R08','R09')), role_name varchar(100) NOT NULL, purpose varchar(500) NOT NULL, grant_criteria varchar(1000), default_data_scope varchar(100), use_yn char(1) NOT NULL CHECK (use_yn IN ('Y','N')), created_at timestamp NOT NULL, updated_at timestamp NOT NULL
);
CREATE TABLE IF NOT EXISTS user_role (
  assignment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id varchar(50) NOT NULL REFERENCES app_user(user_id), role_code varchar(3) NOT NULL REFERENCES role(role_code), assignment_type varchar(20) NOT NULL CHECK (assignment_type IN ('POSITION_BASED','MANUAL')), valid_from date NOT NULL, valid_to date, approver_id varchar(50) REFERENCES app_user(user_id), status varchar(20) NOT NULL CHECK (status IN ('ACTIVE','REVOKED','EXPIRED')), created_at timestamp NOT NULL, updated_at timestamp NOT NULL, CHECK (valid_to IS NULL OR valid_to >= valid_from)
);
CREATE TABLE IF NOT EXISTS menu (
  menu_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, parent_menu_id bigint REFERENCES menu(menu_id), menu_type varchar(20) NOT NULL CHECK (menu_type IN ('TOP','MIDDLE','SCREEN')), menu_name varchar(200) NOT NULL, screen_id varchar(100) UNIQUE, url varchar(300) UNIQUE, icon varchar(100), business_category varchar(100), description varchar(1000), display_order integer NOT NULL, use_yn char(1) NOT NULL CHECK (use_yn IN ('Y','N')), created_at timestamp NOT NULL, updated_at timestamp NOT NULL, CHECK (parent_menu_id IS NULL OR parent_menu_id <> menu_id)
);
CREATE TABLE IF NOT EXISTS menu_permission (
  permission_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, target_type varchar(10) NOT NULL CHECK (target_type IN ('ROLE','ORG','USER')), target_id varchar(50) NOT NULL, menu_id bigint NOT NULL REFERENCES menu(menu_id), access_allowed boolean NOT NULL, created_at timestamp NOT NULL, updated_at timestamp NOT NULL, UNIQUE(target_type,target_id,menu_id)
);
CREATE TABLE IF NOT EXISTS code_group (
  group_id varchar(50) PRIMARY KEY, group_name varchar(200) NOT NULL, description varchar(1000), managing_department varchar(200), use_yn char(1) NOT NULL CHECK (use_yn IN ('Y','N')), created_at timestamp NOT NULL, updated_at timestamp NOT NULL
);
CREATE TABLE IF NOT EXISTS code_detail (
  group_id varchar(50) NOT NULL REFERENCES code_group(group_id), code_value varchar(50) NOT NULL, code_name varchar(200) NOT NULL, parent_code_value varchar(50), sort_order integer NOT NULL, extra_attributes jsonb, valid_from date, valid_to date, use_yn char(1) NOT NULL CHECK (use_yn IN ('Y','N')), created_at timestamp NOT NULL, updated_at timestamp NOT NULL, PRIMARY KEY(group_id, code_value), CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from)
);
CREATE TABLE IF NOT EXISTS session (
  session_id varchar(128) PRIMARY KEY, user_id varchar(50) NOT NULL REFERENCES app_user(user_id), expires_at timestamp NOT NULL, created_at timestamp NOT NULL, updated_at timestamp NOT NULL
);
CREATE TABLE IF NOT EXISTS change_history (
  history_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, entity_name varchar(100) NOT NULL, entity_id varchar(100) NOT NULL, before_value jsonb, after_value jsonb, actor_id varchar(50) NOT NULL REFERENCES app_user(user_id), reason varchar(500), created_at timestamp NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_korus_org ON korus_personnel_snapshot(org_code);
CREATE INDEX IF NOT EXISTS idx_app_user_korus ON app_user(korus_person_id);
CREATE INDEX IF NOT EXISTS idx_user_role_user ON user_role(user_id);
CREATE INDEX IF NOT EXISTS idx_menu_parent ON menu(parent_menu_id);
CREATE INDEX IF NOT EXISTS idx_permission_target ON menu_permission(target_type,target_id);
CREATE INDEX IF NOT EXISTS idx_code_detail_group ON code_detail(group_id);
CREATE INDEX IF NOT EXISTS idx_session_expires ON session(expires_at);
