CREATE TABLE IF NOT EXISTS organization (organization_code varchar(50) PRIMARY KEY, organization_name varchar(200) NOT NULL, organization_type varchar(40) NOT NULL, source_system varchar(30) NOT NULL DEFAULT 'KORUS_MOCK', use_yn char(1) NOT NULL DEFAULT 'Y', status varchar(20) NOT NULL DEFAULT 'ACTIVE', created_at timestamp NOT NULL DEFAULT now(), updated_at timestamp NOT NULL DEFAULT now(), deleted_at timestamp NULL, change_reason varchar(500) NULL);
COMMENT ON TABLE organization IS '대학·대학원·단과대학·학과·부서 기준 조직. 기본정보는 KORUS Mock snapshot 조회 전용 원천으로 사용한다.';
COMMENT ON COLUMN organization.organization_type IS 'UNIVERSITY:대학|GRADUATE_SCHOOL:대학원|COLLEGE:단과대학|DEPARTMENT:학과|ADMIN_DEPARTMENT:행정부서';
COMMENT ON COLUMN organization.status IS 'ACTIVE:활성|INACTIVE:비활성';
COMMENT ON COLUMN organization.use_yn IS 'Y:사용|N:미사용';
CREATE TABLE IF NOT EXISTS korus_staff_snapshot (staff_no varchar(50) PRIMARY KEY, staff_name varchar(100) NOT NULL, organization_code varchar(50) NOT NULL REFERENCES organization(organization_code), position_name varchar(100), job_title varchar(100), employment_status varchar(20) NOT NULL, retirement_date date NULL, last_synced_at timestamp NOT NULL, use_yn char(1) NOT NULL DEFAULT 'Y', created_at timestamp NOT NULL DEFAULT now(), updated_at timestamp NOT NULL DEFAULT now());
COMMENT ON TABLE korus_staff_snapshot IS 'KORUS 원천 인사정보 Mock snapshot. 교번·성명·소속·직급 등 원천 필드는 직접 수정하지 않는다.';
COMMENT ON COLUMN korus_staff_snapshot.employment_status IS 'ACTIVE:재직|LEAVE:휴직|RETIRED:퇴직';
COMMENT ON COLUMN korus_staff_snapshot.use_yn IS 'Y:사용|N:미사용';
CREATE TABLE IF NOT EXISTS user_account (user_id varchar(50) PRIMARY KEY, login_id varchar(100) UNIQUE NOT NULL, password_hash varchar(255) NOT NULL, staff_no varchar(50) REFERENCES korus_staff_snapshot(staff_no), display_name varchar(100) NOT NULL, use_yn char(1) NOT NULL DEFAULT 'Y', status varchar(20) NOT NULL DEFAULT 'ACTIVE', created_at timestamp NOT NULL DEFAULT now(), updated_at timestamp NOT NULL DEFAULT now(), deleted_at timestamp NULL, change_reason varchar(500));
COMMENT ON TABLE user_account IS '로컬 인증과 시스템 사용여부를 관리하는 내부 계정. KORUS 인사 원천과 staff_no로 연결된다.';
COMMENT ON COLUMN user_account.status IS 'ACTIVE:활성|DISABLED:비활성|LOCKED:잠김';
COMMENT ON COLUMN user_account.use_yn IS 'Y:사용|N:미사용';
CREATE TABLE IF NOT EXISTS organization_relation (relation_id bigserial PRIMARY KEY, organization_code varchar(50) NOT NULL REFERENCES organization(organization_code), parent_organization_code varchar(50) NULL REFERENCES organization(organization_code), effective_start_date date NOT NULL, effective_end_date date NULL, status varchar(20) NOT NULL DEFAULT 'ACTIVE', created_at timestamp NOT NULL DEFAULT now(), updated_at timestamp NOT NULL DEFAULT now(), deleted_at timestamp NULL, change_reason varchar(500));
COMMENT ON TABLE organization_relation IS '조직 상하위 관계와 적용기간 이력. 조직 기본정보가 아닌 관계 변경만 로컬 DB에서 관리한다.';
COMMENT ON COLUMN organization_relation.status IS 'ACTIVE:활성|INACTIVE:비활성';
CREATE TABLE IF NOT EXISTS position_user_mapping (mapping_id bigserial PRIMARY KEY, staff_no varchar(50) NOT NULL REFERENCES korus_staff_snapshot(staff_no), organization_code varchar(50) NOT NULL REFERENCES organization(organization_code), position_name varchar(100) NOT NULL, effective_start_date date NOT NULL, effective_end_date date NULL, use_yn char(1) NOT NULL DEFAULT 'Y', created_at timestamp NOT NULL DEFAULT now(), updated_at timestamp NOT NULL DEFAULT now());
COMMENT ON TABLE position_user_mapping IS '보직 기반 역할 산정을 위한 사용자 보직 매핑 snapshot. 수동 역할 회수 대상이 아니다.';
COMMENT ON COLUMN position_user_mapping.use_yn IS 'Y:사용|N:미사용';
CREATE TABLE IF NOT EXISTS role (role_code varchar(10) PRIMARY KEY, role_name varchar(100) NOT NULL, purpose varchar(500) NOT NULL, assignment_criteria varchar(1000), default_data_scope varchar(200), use_yn char(1) NOT NULL DEFAULT 'Y', created_at timestamp NOT NULL DEFAULT now(), updated_at timestamp NOT NULL DEFAULT now(), deleted_at timestamp NULL, change_reason varchar(500));
COMMENT ON TABLE role IS 'R01~R09 업무 역할 기준정보. 역할명은 변경 가능하지만 role_code는 생명주기 식별자로 유지한다.';
COMMENT ON COLUMN role.use_yn IS 'Y:사용|N:미사용';
CREATE TABLE IF NOT EXISTS user_role (assignment_id bigserial PRIMARY KEY, user_id varchar(50) NOT NULL REFERENCES user_account(user_id), role_code varchar(10) NOT NULL REFERENCES role(role_code), assignment_type varchar(20) NOT NULL, approved_by varchar(50) NULL REFERENCES user_account(user_id), effective_start_date date NOT NULL, effective_end_date date NULL, status varchar(20) NOT NULL DEFAULT 'ACTIVE', use_yn char(1) NOT NULL DEFAULT 'Y', created_at timestamp NOT NULL DEFAULT now(), updated_at timestamp NOT NULL DEFAULT now(), deleted_at timestamp NULL, change_reason varchar(500));
COMMENT ON TABLE user_role IS '사용자별 역할 부여 이력. POSITION 역할과 MANUAL 역할을 구분하고 수동 역할만 회수한다.';
COMMENT ON COLUMN user_role.assignment_type IS 'POSITION:보직기반|MANUAL:수동부여';
COMMENT ON COLUMN user_role.status IS 'ACTIVE:활성|REVOKED:회수|EXPIRED:만료';
COMMENT ON COLUMN user_role.use_yn IS 'Y:사용|N:미사용';
CREATE TABLE IF NOT EXISTS menu (menu_id varchar(50) PRIMARY KEY, parent_menu_id varchar(50) NULL REFERENCES menu(menu_id), menu_type varchar(20) NOT NULL, menu_name varchar(200) NOT NULL, screen_id varchar(100), url varchar(300), icon varchar(100), business_category varchar(100), description varchar(1000), display_order integer NOT NULL DEFAULT 0, use_yn char(1) NOT NULL DEFAULT 'Y', created_at timestamp NOT NULL DEFAULT now(), updated_at timestamp NOT NULL DEFAULT now(), deleted_at timestamp NULL, change_reason varchar(500));
COMMENT ON TABLE menu IS '시스템 관리 대·중·소 메뉴 계층과 실행 화면 연결정보. 삭제성 처리는 물리삭제보다 비활성화를 우선한다.';
COMMENT ON COLUMN menu.menu_type IS 'ROOT:대메뉴|GROUP:중메뉴|SCREEN:화면';
COMMENT ON COLUMN menu.use_yn IS 'Y:사용|N:미사용';
CREATE TABLE IF NOT EXISTS menu_permission (permission_id bigserial PRIMARY KEY, target_type varchar(20) NOT NULL, target_id varchar(50) NOT NULL, menu_id varchar(50) NOT NULL REFERENCES menu(menu_id), decision varchar(10) NOT NULL, api_path_pattern varchar(300), use_yn char(1) NOT NULL DEFAULT 'Y', created_at timestamp NOT NULL DEFAULT now(), updated_at timestamp NOT NULL DEFAULT now(), deleted_at timestamp NULL, change_reason varchar(500), CONSTRAINT uq_menu_permission UNIQUE(target_type,target_id,menu_id));
COMMENT ON TABLE menu_permission IS '역할·조직·사용자 대상 메뉴 접근 권한. USER > ORGANIZATION > ROLE 및 DENY 우선 정책의 기준 데이터다.';
COMMENT ON COLUMN menu_permission.target_type IS 'ROLE:역할|ORGANIZATION:조직|USER:사용자';
COMMENT ON COLUMN menu_permission.decision IS 'ALLOW:허용|DENY:거부';
COMMENT ON COLUMN menu_permission.use_yn IS 'Y:사용|N:미사용';
CREATE TABLE IF NOT EXISTS code_group (group_id varchar(50) PRIMARY KEY, group_name varchar(200) NOT NULL, description varchar(1000), managing_department varchar(200), status varchar(20) NOT NULL DEFAULT 'ACTIVE', use_yn char(1) NOT NULL DEFAULT 'Y', created_at timestamp NOT NULL DEFAULT now(), updated_at timestamp NOT NULL DEFAULT now(), deleted_at timestamp NULL, change_reason varchar(500));
COMMENT ON TABLE code_group IS '공통코드 묶음 기준정보. 평가영역·처리상태 등 화면 선택값의 상위 분류를 관리한다.';
COMMENT ON COLUMN code_group.status IS 'ACTIVE:활성|INACTIVE:비활성';
COMMENT ON COLUMN code_group.use_yn IS 'Y:사용|N:미사용';
CREATE TABLE IF NOT EXISTS detail_code (group_id varchar(50) NOT NULL REFERENCES code_group(group_id), code_value varchar(50) NOT NULL, code_name varchar(200) NOT NULL, parent_code_value varchar(50), display_order integer NOT NULL DEFAULT 0, additional_attributes jsonb, effective_start_date date NULL, effective_end_date date NULL, status varchar(20) NOT NULL DEFAULT 'ACTIVE', use_yn char(1) NOT NULL DEFAULT 'Y', created_at timestamp NOT NULL DEFAULT now(), updated_at timestamp NOT NULL DEFAULT now(), deleted_at timestamp NULL, change_reason varchar(500), PRIMARY KEY(group_id, code_value));
COMMENT ON TABLE detail_code IS '코드그룹별 상세코드와 계층·정렬·추가속성. 사용 중인 코드는 비활성화로 처리한다.';
COMMENT ON COLUMN detail_code.status IS 'ACTIVE:활성|INACTIVE:비활성';
COMMENT ON COLUMN detail_code.use_yn IS 'Y:사용|N:미사용';
COMMENT ON COLUMN detail_code.additional_attributes IS 'DetailCodeController 등록·수정 시 애플리케이션에서 갱신하는 추가 속성 JSON';
CREATE TABLE IF NOT EXISTS session (session_id varchar(128) PRIMARY KEY, user_id varchar(50) NOT NULL REFERENCES user_account(user_id), issued_at timestamp NOT NULL, expires_at timestamp NOT NULL, status varchar(20) NOT NULL, client_label varchar(100), created_at timestamp NOT NULL DEFAULT now(), updated_at timestamp NOT NULL DEFAULT now());
COMMENT ON TABLE session IS 'HttpOnly SameSite=Lax 쿠키 기반 로컬 인증 세션. ACTIVE 세션만 보호 API 접근에 사용한다.';
COMMENT ON COLUMN session.status IS 'ACTIVE:활성|EXPIRED:만료|REVOKED:폐기';
CREATE TABLE IF NOT EXISTS change_history (change_id bigserial PRIMARY KEY, entity_name varchar(100) NOT NULL, entity_key varchar(200) NOT NULL, operation_type varchar(20) NOT NULL, before_value jsonb, after_value jsonb, changed_by varchar(50) NOT NULL, changed_at timestamp NOT NULL DEFAULT now(), change_reason varchar(500), status varchar(20) NOT NULL DEFAULT 'ACTIVE', created_at timestamp NOT NULL DEFAULT now(), updated_at timestamp NOT NULL DEFAULT now());
COMMENT ON TABLE change_history IS '관리 기능별 변경 전후 값 추적 구조. 별도 감사로그 운영 화면은 1차 범위에서 제공하지 않는다.';
COMMENT ON COLUMN change_history.changed_by IS 'user_account.user_id 참조 의도 (FK 미선언: seed/system 변경 허용)';
COMMENT ON COLUMN change_history.operation_type IS 'CREATE:등록|UPDATE:수정|DELETE:삭제|DISABLE:비활성화|REVOKE:회수';
COMMENT ON COLUMN change_history.status IS 'ACTIVE:활성|INACTIVE:비활성';
CREATE INDEX IF NOT EXISTS idx_user_account_staff_no ON user_account(staff_no);
CREATE INDEX IF NOT EXISTS idx_user_role_user_id ON user_role(user_id);
CREATE INDEX IF NOT EXISTS idx_menu_parent ON menu(parent_menu_id);
CREATE INDEX IF NOT EXISTS idx_detail_code_group ON detail_code(group_id);
