INSERT INTO organization (organization_code, organization_name, organization_type, source_system, use_yn, status) VALUES
('EDU','교육대학','COLLEGE','KORUS_MOCK','Y','ACTIVE'),('CSE','컴퓨터교육과','DEPARTMENT','KORUS_MOCK','Y','ACTIVE'),('ADMIN','교수지원과','ADMIN_DEPARTMENT','KORUS_MOCK','Y','ACTIVE') ON CONFLICT (organization_code) DO NOTHING;
INSERT INTO organization_relation (organization_code,parent_organization_code,effective_start_date,status,change_reason) VALUES ('EDU','KNUE','2026-01-01','ACTIVE','seed'),('CSE','EDU','2026-01-01','ACTIVE','seed'),('ADMIN','KNUE','2026-01-01','ACTIVE','seed');
INSERT INTO korus_staff_snapshot (staff_no,staff_name,organization_code,position_name,job_title,employment_status,retirement_date,last_synced_at,use_yn) VALUES ('10002','홍길동','CSE','학과장','교수','ACTIVE',NULL,'2026-07-31 09:00:00','Y'),('10003','김교원','CSE',NULL,'부교수','LEAVE',NULL,'2026-07-31 09:00:00','Y') ON CONFLICT (staff_no) DO NOTHING;
INSERT INTO user_account (user_id, login_id, password_hash, staff_no, display_name, use_yn, status) VALUES ('USER-10002','hong','8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918','10002','홍길동','Y','ACTIVE'),('USER-10003','kim','8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918','10003','김교원','Y','ACTIVE') ON CONFLICT (user_id) DO NOTHING;
INSERT INTO position_user_mapping (staff_no,organization_code,position_name,effective_start_date,use_yn) VALUES ('10002','CSE','학과장','2026-01-01','Y') ON CONFLICT DO NOTHING;
INSERT INTO user_role (user_id, role_code, assignment_type, approved_by, effective_start_date, status, use_yn) VALUES ('USER-10002','R02','POSITION','admin','2026-01-01','ACTIVE','Y'),('USER-10003','R01','POSITION','admin','2026-01-01','ACTIVE','Y') ON CONFLICT DO NOTHING;
INSERT INTO code_group (group_id,group_name,description,managing_department,status,use_yn) VALUES ('EVAL_AREA','평가영역','평가영역 선택값','교수지원과','ACTIVE','Y'),('USE_YN','사용여부','공통 사용여부','시스템관리','ACTIVE','Y') ON CONFLICT (group_id) DO NOTHING;
INSERT INTO detail_code (group_id,code_value,code_name,parent_code_value,display_order,additional_attributes,status,use_yn) VALUES ('EVAL_AREA','TEACHING','교육',NULL,10,'{}','ACTIVE','Y'),('EVAL_AREA','LECTURE','강의','TEACHING',20,'{}','ACTIVE','Y'),('USE_YN','Y','사용',NULL,1,'{}','ACTIVE','Y'),('USE_YN','N','미사용',NULL,2,'{}','ACTIVE','Y') ON CONFLICT (group_id,code_value) DO NOTHING;
