CREATE TABLE IF NOT EXISTS org (
    org_code varchar(30) PRIMARY KEY,
    org_name varchar(200) NOT NULL,
    org_type varchar(30) NOT NULL CHECK (org_type IN ('UNIVERSITY','GRADUATE_SCHOOL','COLLEGE','DEPARTMENT','OFFICE')),
    use_yn char(1) NOT NULL CHECK (use_yn IN ('Y','N')),
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL
);
COMMENT ON TABLE org IS '대학·대학원·단과대학·학과·부서 기준 조직.';
COMMENT ON COLUMN org.org_type IS 'UNIVERSITY:대학|GRADUATE_SCHOOL:대학원|COLLEGE:단과대학|DEPARTMENT:학과|OFFICE:부서';
COMMENT ON COLUMN org.use_yn IS 'Y:사용|N:미사용';

CREATE TABLE IF NOT EXISTS korus_personnel_snapshot (
    person_id varchar(50) PRIMARY KEY,
    name varchar(100) NOT NULL,
    org_code varchar(30) REFERENCES org(org_code),
    position_name varchar(100),
    rank_name varchar(100),
    employment_status varchar(30),
    retired_at date,
    last_synced_at timestamp NOT NULL,
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL
);
COMMENT ON TABLE korus_personnel_snapshot IS 'KORUS 교직원 원천정보 조회 전용 Mock snapshot.';
COMMENT ON COLUMN korus_personnel_snapshot.employment_status IS 'ACTIVE:재직|LEAVE:휴직|RETIRED:퇴직';

CREATE TABLE IF NOT EXISTS app_user (
    user_id varchar(50) PRIMARY KEY,
    korus_person_id varchar(50) REFERENCES korus_personnel_snapshot(person_id),
    password_hash varchar(255) NOT NULL,
    use_yn char(1) NOT NULL CHECK (use_yn IN ('Y','N')),
    status varchar(20) NOT NULL CHECK (status IN ('ACTIVE','INACTIVE','REVOKED')),
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL
);
COMMENT ON TABLE app_user IS '내부 로그인 계정과 시스템 사용여부를 관리하는 사용자 계정.';
COMMENT ON COLUMN app_user.use_yn IS 'Y:사용|N:미사용';
COMMENT ON COLUMN app_user.status IS 'ACTIVE:활성|INACTIVE:비활성|REVOKED:회수';

CREATE TABLE IF NOT EXISTS org_relation (
    relation_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_code varchar(30) NOT NULL REFERENCES org(org_code),
    parent_org_code varchar(30) REFERENCES org(org_code),
    valid_from date NOT NULL,
    valid_to date,
    change_reason varchar(500),
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL,
    CONSTRAINT ck_org_relation_date CHECK (valid_to IS NULL OR valid_to >= valid_from),
    CONSTRAINT ck_org_relation_self CHECK (parent_org_code IS NULL OR parent_org_code <> org_code)
);
COMMENT ON TABLE org_relation IS '조직 상하위 관계와 적용기간 이력을 저장한다.';

CREATE TABLE IF NOT EXISTS org_user_position (
    mapping_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id varchar(50) NOT NULL REFERENCES korus_personnel_snapshot(person_id),
    org_code varchar(30) NOT NULL REFERENCES org(org_code),
    position_name varchar(100),
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL
);
COMMENT ON TABLE org_user_position IS '교직원의 조직별 보직 매핑 정보를 저장한다.';

CREATE TABLE IF NOT EXISTS role (
    role_code varchar(3) PRIMARY KEY,
    role_name varchar(100) NOT NULL,
    purpose varchar(500) NOT NULL,
    grant_criteria varchar(1000),
    default_data_scope varchar(100),
    use_yn char(1) NOT NULL CHECK (use_yn IN ('Y','N')),
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL
);
COMMENT ON TABLE role IS 'R01~R09 업무 역할 정의와 부여 기준을 관리한다.';
COMMENT ON COLUMN role.role_code IS 'R01:교원|R02:학과장|R03:단과대학행정실|R04:교수지원과|R05:산학협력단|R06:입학인재관리과|R07:실적부서|R08:점수산출감사자|R09:시스템관리자';
COMMENT ON COLUMN role.use_yn IS 'Y:사용|N:미사용';

CREATE TABLE IF NOT EXISTS user_role (
    assignment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id varchar(50) NOT NULL REFERENCES app_user(user_id),
    role_code varchar(3) NOT NULL REFERENCES role(role_code),
    assignment_type varchar(20) NOT NULL CHECK (assignment_type IN ('POSITION_BASED','MANUAL')),
    valid_from date NOT NULL,
    valid_to date,
    approver_id varchar(50) REFERENCES app_user(user_id),
    status varchar(20) NOT NULL CHECK (status IN ('ACTIVE','REVOKED','EXPIRED')),
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL,
    CONSTRAINT ck_user_role_date CHECK (valid_to IS NULL OR valid_to >= valid_from)
);
COMMENT ON TABLE user_role IS '사용자별 업무 역할 배정과 유효기간, 승인자 및 회수 상태를 기록한다.';
COMMENT ON COLUMN user_role.assignment_type IS 'POSITION_BASED:보직기반|MANUAL:수동';
COMMENT ON COLUMN user_role.status IS 'ACTIVE:활성|REVOKED:회수|EXPIRED:만료';

CREATE TABLE IF NOT EXISTS menu (
    menu_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_menu_id bigint REFERENCES menu(menu_id),
    menu_type varchar(20) NOT NULL CHECK (menu_type IN ('TOP','MIDDLE','SCREEN')),
    menu_name varchar(200) NOT NULL,
    screen_id varchar(100) UNIQUE,
    url varchar(300) UNIQUE,
    icon varchar(100),
    business_category varchar(100),
    description varchar(1000),
    display_order integer NOT NULL,
    use_yn char(1) NOT NULL CHECK (use_yn IN ('Y','N')),
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL,
    CONSTRAINT ck_menu_self CHECK (parent_menu_id IS NULL OR parent_menu_id <> menu_id)
);
COMMENT ON TABLE menu IS '시스템 관리 메뉴 계층, 화면 연결 정보, 표시순서를 관리한다.';
COMMENT ON COLUMN menu.menu_type IS 'TOP:대메뉴|MIDDLE:중메뉴|SCREEN:화면';
COMMENT ON COLUMN menu.use_yn IS 'Y:사용|N:미사용';

CREATE TABLE IF NOT EXISTS menu_permission (
    permission_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type varchar(10) NOT NULL CHECK (target_type IN ('ROLE','ORG','USER')),
    target_id varchar(50) NOT NULL,
    menu_id bigint NOT NULL REFERENCES menu(menu_id),
    access_allowed boolean NOT NULL,
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL,
    UNIQUE (target_type, target_id, menu_id)
);
COMMENT ON TABLE menu_permission IS '역할·조직·사용자 대상별 메뉴 접근 가능 여부를 저장한다.';
COMMENT ON COLUMN menu_permission.target_type IS 'ROLE:역할|ORG:조직|USER:사용자';
COMMENT ON COLUMN menu_permission.target_id IS 'role.role_code, org.org_code 또는 app_user.user_id 참조 의도 (다형 대상)';

CREATE TABLE IF NOT EXISTS code_group (
    group_id varchar(50) PRIMARY KEY,
    group_name varchar(200) NOT NULL,
    description varchar(1000),
    managing_department varchar(200),
    use_yn char(1) NOT NULL CHECK (use_yn IN ('Y','N')),
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL
);
COMMENT ON TABLE code_group IS '공통코드 묶음의 그룹 식별자, 명칭, 관리부서를 저장한다.';
COMMENT ON COLUMN code_group.use_yn IS 'Y:사용|N:미사용';

CREATE TABLE IF NOT EXISTS code_detail (
    group_id varchar(50) NOT NULL REFERENCES code_group(group_id),
    code_value varchar(50) NOT NULL,
    code_name varchar(200) NOT NULL,
    parent_code_value varchar(50),
    sort_order integer NOT NULL,
    extra_attributes jsonb,
    valid_from date,
    valid_to date,
    use_yn char(1) NOT NULL CHECK (use_yn IN ('Y','N')),
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL,
    PRIMARY KEY (group_id, code_value),
    CONSTRAINT ck_code_detail_date CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from)
);
COMMENT ON TABLE code_detail IS '코드그룹에 속한 상세코드 값, 계층, 정렬, 유효기간과 확장속성을 관리한다.';
COMMENT ON COLUMN code_detail.use_yn IS 'Y:사용|N:미사용';
COMMENT ON COLUMN code_detail.extra_attributes IS 'CodeService.create/update 시 요청 JSON으로 갱신';

CREATE TABLE IF NOT EXISTS "session" (
    session_id varchar(128) PRIMARY KEY,
    user_id varchar(50) NOT NULL REFERENCES app_user(user_id),
    expires_at timestamp NOT NULL,
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL
);
COMMENT ON TABLE "session" IS '로그인 세션 쿠키와 만료일시를 저장한다.';

CREATE TABLE IF NOT EXISTS change_history (
    history_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_name varchar(100) NOT NULL,
    entity_id varchar(100) NOT NULL,
    before_value jsonb,
    after_value jsonb,
    actor_id varchar(50) NOT NULL REFERENCES app_user(user_id),
    reason varchar(500),
    created_at timestamp NOT NULL
);
COMMENT ON TABLE change_history IS '등록·수정·삭제성 처리의 변경 전후값, 처리자, 사유를 추적한다.';
COMMENT ON COLUMN change_history.actor_id IS 'app_user.user_id 참조';

CREATE INDEX IF NOT EXISTS ix_app_user_korus_person_id ON app_user(korus_person_id);
CREATE INDEX IF NOT EXISTS ix_user_role_user_status ON user_role(user_id, status);
CREATE INDEX IF NOT EXISTS ix_menu_parent_order ON menu(parent_menu_id, display_order);
CREATE INDEX IF NOT EXISTS ix_menu_permission_target ON menu_permission(target_type, target_id);
CREATE INDEX IF NOT EXISTS ix_code_detail_group_order ON code_detail(group_id, sort_order);
CREATE INDEX IF NOT EXISTS ix_session_expires_at ON "session"(expires_at);
CREATE INDEX IF NOT EXISTS ix_change_history_entity ON change_history(entity_name, entity_id);
