CREATE TABLE IF NOT EXISTS role (
  role_code varchar(3) PRIMARY KEY,
  role_name varchar(100) NOT NULL,
  purpose text NOT NULL,
  grant_criteria text NOT NULL,
  default_data_scope varchar(50) NOT NULL,
  use_yn char(1) NOT NULL DEFAULT 'Y' CHECK (use_yn IN ('Y','N')),
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE role IS '교수업적평가시스템 공통기능에서 사용하는 업무 역할 기준정보.';
COMMENT ON COLUMN role.use_yn IS 'Y:사용|N:미사용';

CREATE TABLE IF NOT EXISTS organization (
  org_code varchar(20) PRIMARY KEY,
  org_name varchar(150) NOT NULL,
  org_type varchar(30) NOT NULL,
  parent_org_code varchar(20),
  start_date date NOT NULL,
  end_date date,
  status varchar(20) NOT NULL DEFAULT 'ACTIVE',
  changed_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_organization_parent FOREIGN KEY (parent_org_code) REFERENCES organization(org_code)
);
COMMENT ON TABLE organization IS 'KORUS Mock 조직 스냅샷과 로컬 상하위 관계 적용기간을 관리한다.';
COMMENT ON COLUMN organization.status IS 'ACTIVE:활성|INACTIVE:비활성';


CREATE TABLE IF NOT EXISTS korus_personnel_snapshot (
  employee_no varchar(30) PRIMARY KEY,
  person_name varchar(100) NOT NULL,
  org_code varchar(20) NOT NULL,
  org_name varchar(150) NOT NULL,
  position_name varchar(100),
  duty_name varchar(100),
  employment_status varchar(20) NOT NULL,
  retirement_date date,
  last_synced_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  snapshot_status varchar(20) NOT NULL DEFAULT 'ACTIVE',
  source_system varchar(30) NOT NULL DEFAULT 'KORUS_MOCK',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE korus_personnel_snapshot IS 'KORUS 원천 인사 정보를 로컬 실행용 Mock snapshot으로 보관하며 조회 전용으로만 사용한다.';
COMMENT ON COLUMN korus_personnel_snapshot.org_code IS 'organization.org_code 참조 의도 (Mock 원천 스냅샷이므로 FK 미선언)';
COMMENT ON COLUMN korus_personnel_snapshot.employment_status IS 'ACTIVE:재직|RETIRED:퇴직|LEAVE:휴직';
COMMENT ON COLUMN korus_personnel_snapshot.snapshot_status IS 'ACTIVE:최신|STALE:만료|DELETED:원천삭제';
COMMENT ON COLUMN korus_personnel_snapshot.source_system IS 'KORUS_MOCK:로컬Mock';


CREATE TABLE IF NOT EXISTS user_account (
  user_id varchar(30) PRIMARY KEY,
  login_id varchar(60) NOT NULL UNIQUE,
  password_hash varchar(255) NOT NULL,
  employee_no varchar(30) NOT NULL UNIQUE,
  user_name varchar(100) NOT NULL,
  org_code varchar(20) REFERENCES organization(org_code),
  org_name varchar(150) NOT NULL,
  position_name varchar(100),
  duty_name varchar(100),
  employment_status varchar(20) NOT NULL,
  retirement_date date,
  last_synced_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  system_use_yn char(1) NOT NULL DEFAULT 'Y' CHECK (system_use_yn IN ('Y','N')),
  korus_source_yn char(1) NOT NULL DEFAULT 'Y' CHECK (korus_source_yn IN ('Y','N')),
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE user_account IS 'KORUS 조회 전용 인사 스냅샷과 내부 시스템 사용여부를 연결해 관리한다.';
COMMENT ON COLUMN user_account.system_use_yn IS 'Y:사용|N:미사용';
COMMENT ON COLUMN user_account.korus_source_yn IS 'Y:KORUS스냅샷|N:로컬계정';

CREATE TABLE IF NOT EXISTS user_role_assignment (
  assignment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id varchar(30) NOT NULL REFERENCES user_account(user_id),
  role_code varchar(3) NOT NULL REFERENCES role(role_code),
  valid_from date NOT NULL,
  valid_to date,
  approver_id varchar(30),
  assignment_source varchar(20) NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'ACTIVE',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE user_role_assignment IS '사용자별 역할 부여, 유효기간, 승인자와 보직 기반/수동 출처를 기록한다.';
COMMENT ON COLUMN user_role_assignment.approver_id IS 'user_account.user_id 참조 의도 (FK 미선언)';
COMMENT ON COLUMN user_role_assignment.assignment_source IS 'POSITION:보직기반|MANUAL:수동';
COMMENT ON COLUMN user_role_assignment.status IS 'ACTIVE:유효|REVOKED:회수|EXPIRED:만료';

CREATE TABLE IF NOT EXISTS menu (
  menu_id varchar(40) PRIMARY KEY,
  parent_menu_id varchar(40),
  menu_name varchar(120) NOT NULL,
  screen_id varchar(40),
  route_path varchar(200),
  icon_name varchar(60),
  business_area varchar(60) NOT NULL,
  description text,
  sort_order integer NOT NULL DEFAULT 0,
  use_yn char(1) NOT NULL DEFAULT 'Y' CHECK (use_yn IN ('Y','N')),
  status varchar(20) NOT NULL DEFAULT 'ACTIVE',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_menu_parent FOREIGN KEY (parent_menu_id) REFERENCES menu(menu_id)
);
COMMENT ON TABLE menu IS '시스템 관리 메뉴 계층, route, 화면ID와 비활성화 우선 정책을 관리한다.';
COMMENT ON COLUMN menu.use_yn IS 'Y:사용|N:미사용';
COMMENT ON COLUMN menu.status IS 'ACTIVE:활성|INACTIVE:비활성';

CREATE TABLE IF NOT EXISTS menu_permission (
  permission_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_type varchar(20) NOT NULL,
  target_id varchar(60) NOT NULL,
  menu_id varchar(40) NOT NULL REFERENCES menu(menu_id),
  can_read char(1) NOT NULL DEFAULT 'N' CHECK (can_read IN ('Y','N')),
  can_create char(1) NOT NULL DEFAULT 'N' CHECK (can_create IN ('Y','N')),
  can_update char(1) NOT NULL DEFAULT 'N' CHECK (can_update IN ('Y','N')),
  can_disable char(1) NOT NULL DEFAULT 'N' CHECK (can_disable IN ('Y','N')),
  can_access char(1) NOT NULL DEFAULT 'N' CHECK (can_access IN ('Y','N')),
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_menu_permission_target UNIQUE (target_type, target_id, menu_id)
);
COMMENT ON TABLE menu_permission IS '역할·조직·사용자별 메뉴 접근과 기능 권한을 서버와 화면에 동일하게 제공한다.';
COMMENT ON COLUMN menu_permission.target_type IS 'ROLE:역할|ORG:조직|USER:사용자';
COMMENT ON COLUMN menu_permission.can_read IS 'Y:허용|N:차단';
COMMENT ON COLUMN menu_permission.can_create IS 'Y:허용|N:차단';
COMMENT ON COLUMN menu_permission.can_update IS 'Y:허용|N:차단';
COMMENT ON COLUMN menu_permission.can_disable IS 'Y:허용|N:차단';
COMMENT ON COLUMN menu_permission.can_access IS 'Y:허용|N:차단';

CREATE TABLE IF NOT EXISTS code_group (
  group_id varchar(40) PRIMARY KEY,
  group_name varchar(120) NOT NULL,
  description text,
  managing_department varchar(120) NOT NULL,
  use_yn char(1) NOT NULL DEFAULT 'Y' CHECK (use_yn IN ('Y','N')),
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE code_group IS '평가영역, 처리상태, 인증구분 등 공통코드 묶음을 관리한다.';
COMMENT ON COLUMN code_group.use_yn IS 'Y:사용|N:미사용';

CREATE TABLE IF NOT EXISTS detail_code (
  group_id varchar(40) NOT NULL REFERENCES code_group(group_id),
  code_value varchar(60) NOT NULL,
  code_name varchar(120) NOT NULL,
  parent_code_value varchar(60),
  sort_order integer NOT NULL DEFAULT 0,
  use_yn char(1) NOT NULL DEFAULT 'Y' CHECK (use_yn IN ('Y','N')),
  valid_from date NOT NULL,
  valid_to date,
  extra_attributes text,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (group_id, code_value)
);
COMMENT ON TABLE detail_code IS '코드그룹별 코드값, 코드명, 정렬, 사용여부, 유효기간과 추가 속성을 관리한다.';
COMMENT ON COLUMN detail_code.parent_code_value IS 'detail_code.code_value 참조 의도 (동일 group_id 내 FK 미선언)';
COMMENT ON COLUMN detail_code.use_yn IS 'Y:사용|N:미사용';
COMMENT ON COLUMN detail_code.extra_attributes IS 'CodeAdminService 등록·수정 시 애플리케이션에서 갱신';

CREATE TABLE IF NOT EXISTS session_store (
  session_id varchar(80) PRIMARY KEY,
  user_id varchar(30) NOT NULL REFERENCES user_account(user_id),
  expires_at timestamp NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE session_store IS '로컬 Mock 인증 세션과 시드 관리자 로그인 상태를 저장한다.';

CREATE TABLE IF NOT EXISTS change_history (
  history_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_name varchar(80) NOT NULL,
  entity_id varchar(120) NOT NULL,
  action_type varchar(30) NOT NULL,
  before_value text,
  after_value text,
  reason text NOT NULL,
  actor_id varchar(30),
  processed_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE change_history IS '등록·수정·삭제성 처리의 변경 전후 값, 처리자, 처리일시와 사유를 추적한다.';
COMMENT ON COLUMN change_history.action_type IS 'CREATE:등록|UPDATE:수정|DISABLE:비활성|REVOKE:회수|DELETE:삭제요청';
COMMENT ON COLUMN change_history.actor_id IS 'user_account.user_id 참조 의도 (FK 미선언)';

CREATE TABLE IF NOT EXISTS delivery_status (
  status_key varchar(60) PRIMARY KEY,
  status_value varchar(120) NOT NULL,
  description text NOT NULL,
  checked_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE delivery_status IS '산출물, Mock, seed, health와 1차 범위 제외 상태를 검증 대시보드에 제공한다.';

CREATE INDEX IF NOT EXISTS idx_user_account_search ON user_account(user_name, org_code, employment_status, system_use_yn);
CREATE INDEX IF NOT EXISTS idx_korus_personnel_snapshot_search ON korus_personnel_snapshot(person_name, org_code, employment_status, snapshot_status);
CREATE INDEX IF NOT EXISTS idx_user_role_user ON user_role_assignment(user_id, status);
CREATE INDEX IF NOT EXISTS idx_menu_parent ON menu(parent_menu_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_detail_code_group_order ON detail_code(group_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_change_history_entity ON change_history(entity_name, entity_id);

DELETE FROM delivery_status WHERE status_key IN ('backend','frontend','database','korus_snapshot','scope_guard','handoff');
DELETE FROM detail_code WHERE (group_id = 'SYSTEM_STATUS' AND code_value IN ('ACTIVE','INACTIVE')) OR (group_id = 'EMPLOYMENT_STATUS' AND code_value IN ('ACTIVE','RETIRED')) OR (group_id = 'ROLE_SOURCE' AND code_value IN ('POSITION','MANUAL'));
DELETE FROM code_group WHERE group_id IN ('SYSTEM_STATUS','EMPLOYMENT_STATUS','ROLE_SOURCE');
DELETE FROM menu_permission WHERE target_type = 'ROLE' AND target_id = 'R09';
DELETE FROM menu WHERE menu_id IN ('M-DETAIL-CODES','M-CODE-GROUPS','M-MENU-INFO','M-MENU-TREE','M-MENU-PERM','M-USER-ROLES','M-ROLES','M-ORGS','M-USERS','SYS-CODE','SYS-MENU','SYS-RP','SYS-UO','SYS');
DELETE FROM user_role_assignment WHERE user_id IN ('USR-ADMIN','USR-1001') AND role_code IN ('R09','R01','R02');
DELETE FROM user_account WHERE user_id IN ('USR-ADMIN','USR-1001','USR-1002');
DELETE FROM korus_personnel_snapshot WHERE employee_no IN ('1001','1002');
DELETE FROM organization WHERE org_code IN ('DEP-COM','DEP-ADM','COL-EDU','KNUE');
DELETE FROM role WHERE role_code IN ('R01','R02','R03','R04','R05','R06','R07','R08','R09');

INSERT INTO role(role_code, role_name, purpose, grant_criteria, default_data_scope) VALUES
('R01','교원','본인 관련 업무 수행','재직 교원 기본 부여','SELF'),
('R02','학과장','소속 학과 교원 업무 확인','학과장 보직자','DEPARTMENT'),
('R03','단과대학(원) 행정실','단과대학 또는 대학원 행정 처리','단과대학 행정 보직자','COLLEGE'),
('R04','교수지원과','기준정보와 평가 관련 행정 관리','교수지원과 담당자','ALL'),
('R05','산학협력단','연구비·간접비·지식재산 자료 관리','산학협력단 담당자','RESEARCH'),
('R06','입학인재관리과','입학·취업률 자료 관리','입학인재관리과 담당자','ADMISSION'),
('R07','실적부서','담당 실적 자료 관리','실적 부서 담당자','OWN_DEPT'),
('R08','점수산출 감사자','산출 과정과 근거 조회','감사자 지정','AUDIT'),
('R09','시스템관리자','사용자·조직·메뉴·권한·코드 관리','시스템 관리자 지정','ALL');

INSERT INTO organization(org_code, org_name, org_type, parent_org_code, start_date, end_date, status) VALUES
('KNUE','한국교원대학교','UNIVERSITY',NULL,'1984-03-01',NULL,'ACTIVE'),
('COL-EDU','교육대학','COLLEGE','KNUE','1984-03-01',NULL,'ACTIVE'),
('DEP-COM','컴퓨터교육과','DEPARTMENT','COL-EDU','1990-03-01',NULL,'ACTIVE'),
('DEP-ADM','교수지원과','DEPARTMENT','KNUE','2000-01-01',NULL,'ACTIVE');

INSERT INTO korus_personnel_snapshot(employee_no, person_name, org_code, org_name, position_name, duty_name, employment_status, retirement_date, snapshot_status, source_system) VALUES
('1001','김교원','DEP-COM','컴퓨터교육과','교수','학과장','ACTIVE',NULL,'ACTIVE','KORUS_MOCK'),
('1002','이교원','DEP-COM','컴퓨터교육과','부교수',NULL,'ACTIVE',NULL,'ACTIVE','KORUS_MOCK');

INSERT INTO user_account(user_id, login_id, password_hash, employee_no, user_name, org_code, org_name, position_name, duty_name, employment_status, retirement_date, system_use_yn, korus_source_yn) VALUES
('USR-ADMIN','admin','{noop}admin','A0001','시스템관리자','DEP-ADM','교수지원과','직원','시스템관리자','ACTIVE',NULL,'Y','N'),
('USR-1001','prof1001','{noop}unused','1001','김교원','DEP-COM','컴퓨터교육과','교수','학과장','ACTIVE',NULL,'Y','Y'),
('USR-1002','prof1002','{noop}unused','1002','이교원','DEP-COM','컴퓨터교육과','부교수',NULL,'ACTIVE',NULL,'Y','Y');

INSERT INTO user_role_assignment(user_id, role_code, valid_from, valid_to, approver_id, assignment_source, status) VALUES
('USR-ADMIN','R09','2026-01-01',NULL,'USR-ADMIN','MANUAL','ACTIVE'),
('USR-1001','R01','2026-01-01',NULL,'USR-ADMIN','POSITION','ACTIVE'),
('USR-1001','R02','2026-01-01',NULL,'USR-ADMIN','POSITION','ACTIVE');

INSERT INTO menu(menu_id,parent_menu_id,menu_name,screen_id,route_path,icon_name,business_area,description,sort_order,use_yn,status) VALUES
('SYS',NULL,'시스템 관리',NULL,NULL,'settings','COMMON','시스템 관리 대메뉴',1,'Y','ACTIVE'),
('SYS-UO','SYS','사용자·조직 관리',NULL,NULL,'users','COMMON','사용자와 조직 관리',1,'Y','ACTIVE'),
('SYS-RP','SYS','역할·권한 관리',NULL,NULL,'shield','COMMON','역할과 권한 관리',2,'Y','ACTIVE'),
('SYS-MENU','SYS','메뉴 관리',NULL,NULL,'menu','COMMON','메뉴 구조와 실행정보 관리',3,'Y','ACTIVE'),
('SYS-CODE','SYS','공통코드 관리',NULL,NULL,'code','COMMON','공통코드 관리',4,'Y','ACTIVE'),
('M-USERS','SYS-UO','사용자 관리','SCR-USERS','/system/users','user','COMMON','사용자 검색 및 역할 관리',1,'Y','ACTIVE'),
('M-ORGS','SYS-UO','조직 관리','SCR-ORGS','/system/organizations','tree','COMMON','조직 계층 관리',2,'Y','ACTIVE'),
('M-ROLES','SYS-RP','역할 관리','SCR-ROLES','/system/roles','key','COMMON','역할 기준 관리',1,'Y','ACTIVE'),
('M-USER-ROLES','SYS-RP','사용자 역할 관리','SCR-USER-ROLES','/system/user-roles','badge','COMMON','사용자 역할 부여 관리',2,'Y','ACTIVE'),
('M-MENU-PERM','SYS-RP','메뉴 권한 관리','SCR-MENU-PERMISSIONS','/system/menu-permissions','lock','COMMON','메뉴 접근 권한 관리',3,'Y','ACTIVE'),
('M-MENU-TREE','SYS-MENU','메뉴 구조 관리','SCR-MENU-TREE','/system/menu-tree','sitemap','COMMON','메뉴 부모와 순서 관리',1,'Y','ACTIVE'),
('M-MENU-INFO','SYS-MENU','메뉴 정보 관리','SCR-MENU-INFO','/system/menus','file','COMMON','메뉴 실행정보 관리',2,'Y','ACTIVE'),
('M-CODE-GROUPS','SYS-CODE','코드그룹 관리','SCR-CODE-GROUPS','/system/code-groups','folder','COMMON','코드그룹 관리',1,'Y','ACTIVE'),
('M-DETAIL-CODES','SYS-CODE','상세코드 관리','SCR-DETAIL-CODES','/system/code-groups/SYSTEM_STATUS/codes','list','COMMON','상세코드 관리',2,'Y','ACTIVE');

INSERT INTO menu_permission(target_type,target_id,menu_id,can_read,can_create,can_update,can_disable,can_access)
SELECT 'ROLE','R09',menu_id,'Y','Y','Y','Y','Y' FROM menu;

INSERT INTO code_group(group_id, group_name, description, managing_department, use_yn) VALUES
('SYSTEM_STATUS','시스템 상태','공통 활성/비활성 상태','교수지원과','Y'),
('EMPLOYMENT_STATUS','재직 상태','KORUS 재직 상태 코드','교수지원과','Y'),
('ROLE_SOURCE','역할 부여 출처','보직 기반 또는 수동 역할 출처','교수지원과','Y');

INSERT INTO detail_code(group_id, code_value, code_name, parent_code_value, sort_order, use_yn, valid_from, valid_to, extra_attributes) VALUES
('SYSTEM_STATUS','ACTIVE','활성',NULL,1,'Y','2026-01-01',NULL,'{}'),
('SYSTEM_STATUS','INACTIVE','비활성',NULL,2,'Y','2026-01-01',NULL,'{}'),
('EMPLOYMENT_STATUS','ACTIVE','재직',NULL,1,'Y','2026-01-01',NULL,'{}'),
('EMPLOYMENT_STATUS','RETIRED','퇴직',NULL,2,'Y','2026-01-01',NULL,'{}'),
('ROLE_SOURCE','POSITION','보직기반',NULL,1,'Y','2026-01-01',NULL,'{}'),
('ROLE_SOURCE','MANUAL','수동',NULL,2,'Y','2026-01-01',NULL,'{}');

INSERT INTO delivery_status(status_key,status_value,description) VALUES
('backend','READY','Spring Boot 3.3.x, Java 17, MyBatis blocking backend'),
('frontend','READY','React 18, TypeScript, Vite 5, nginx /api proxy frontend'),
('database','READY','PostgreSQL 16 Flyway migration with KORUS Mock snapshot seed data'),
('korus_snapshot','READY','korus_personnel_snapshot 조회 전용 Mock 원천 인사 테이블'),
('scope_guard','READY','1차 범위 밖 업무 데이터 기능은 생성하지 않음'),
('handoff','CLARIFICATION_REQUIRED','plan 계약의 decision_status를 build-ready로 표시하지 않음');
