package kr.ac.knue.common.admin;

import kr.ac.knue.common.api.GlobalExceptionHandler.AppException;
import kr.ac.knue.common.auth.AuthService;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDate;
import java.util.*;

@Service
public class AdminService {
  private final AdminMapper mapper;
  public AdminService(AdminMapper mapper) { this.mapper = mapper; }
  public Map<String,Object> menuContext(AuthService.LoginUser user) { return Map.of("roleCodes", user.roleCodes(), "menus", mapper.menus(Map.of("useYn","Y"))); }
  public List<Map<String,Object>> users(Map<String,Object> p){ return mapper.searchUsers(p); }
  public List<Map<String,Object>> organizations(Map<String,Object> p){ return mapper.organizations(p); }
  public List<Map<String,Object>> roles(Map<String,Object> p){ return mapper.roles(p); }
  public List<Map<String,Object>> assignments(Map<String,Object> p){ return mapper.assignments(p); }
  public List<Map<String,Object>> permissions(Map<String,Object> p){ return mapper.permissions(p); }
  public List<Map<String,Object>> menus(Map<String,Object> p){ return mapper.menus(p); }
  public List<Map<String,Object>> codeGroups(Map<String,Object> p){ return mapper.codeGroups(p); }
  public List<Map<String,Object>> codes(String groupId, Map<String,Object> p){ Map<String,Object> q=new HashMap<>(p); q.put("groupId", groupId); return mapper.codes(q); }
  static void requireReason(Map<String,Object> p){ Object v=p.get("changeReason"); if(v==null || String.valueOf(v).isBlank()) throw new AppException(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR","changeReason은 필수입니다."); }
  static String text(Map<String,Object> p,String k){ Object v=p.get(k); return v==null?null:String.valueOf(v); }
  static String yn(Map<String,Object> p,String k){ String v=text(p,k); if(!"Y".equals(v)&&!"N".equals(v)) throw new AppException(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR",k+"는 Y 또는 N이어야 합니다."); return v; }
  @Transactional public Map<String,Object> updateUserAccess(String userId, Map<String,Object> p, String by){ requireReason(p); String yn=yn(p,"systemUseYn"); mapper.updateUserAccess(userId, yn); mapper.insertHistory("user_account",userId,null,Map.of("systemUseYn",yn),by,text(p,"changeReason")); return mapper.searchUsers(Map.of("employeeNo",userId)).stream().findFirst().orElseThrow(); }
  @Transactional public List<Map<String,Object>> replaceRoles(String userId, Map<String,Object> p, String by){ requireReason(p); List<?> codes=(List<?>)p.get("roleCodes"); if(codes==null||codes.isEmpty()) throw new AppException(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR","roleCodes는 하나 이상이어야 합니다."); if(text(p,"approverUserId")==null||text(p,"validFrom")==null) throw new AppException(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR","approverUserId와 validFrom은 필수입니다."); mapper.revokeManualRoles(userId); for(Object c:codes){ Map<String,Object> row=new HashMap<>(p); row.put("userId",userId); row.put("roleCode",String.valueOf(c)); row.put("grantType","MANUAL"); mapper.insertAssignment(row);} mapper.insertHistory("user_role_assignment",userId,null,p,by,text(p,"changeReason")); return mapper.assignments(Map.of("userId",userId)); }
  @Transactional public Map<String,Object> updateOrgRelation(String code, Map<String,Object> p, String by){ requireReason(p); if(text(p,"effectiveStartDate")==null) throw new AppException(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR","effectiveStartDate는 필수입니다."); if(Objects.equals(code,text(p,"parentOrganizationCode"))) throw new AppException(HttpStatus.BAD_REQUEST,"INVALID_RELATION","상위조직은 자기 자신일 수 없습니다."); LocalDate start=LocalDate.parse(text(p,"effectiveStartDate")); mapper.closeOrgRelation(code,start.minusDays(1).toString()); Map<String,Object> row=new HashMap<>(p); row.put("organizationCode",code); mapper.insertOrgRelation(row); mapper.insertHistory("organization_relation_history",code,null,p,by,text(p,"changeReason")); return mapper.organizations(Map.of("organizationCode",code)).stream().findFirst().orElseThrow(); }
  @Transactional public Map<String,Object> createRole(String roleCode, Map<String,Object> p, String by){ requireReason(p); p.put("roleCode",roleCode); mapper.insertRole(defaultUse(p)); mapper.insertHistory("role",roleCode,null,p,by,text(p,"changeReason")); return mapper.roles(Map.of("roleCode",roleCode)).get(0); }
  @Transactional public Map<String,Object> updateRole(String roleCode, Map<String,Object> p, String by){ requireReason(p); p.put("roleCode",roleCode); mapper.updateRole(defaultUse(p)); mapper.insertHistory("role",roleCode,null,p,by,text(p,"changeReason")); return mapper.roles(Map.of("roleCode",roleCode)).get(0); }
  Map<String,Object> defaultUse(Map<String,Object> p){ if(p.get("useYn")==null)p.put("useYn","Y"); return p; }
  @Transactional public Map<String,Object> grantAssignment(Map<String,Object> p,String by){ requireReason(p); if(text(p,"userId")==null||text(p,"roleCode")==null||text(p,"approverUserId")==null||text(p,"validFrom")==null) throw new AppException(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR","사용자, 역할, 승인자, 유효시작일은 필수입니다."); if(p.get("grantType")==null)p.put("grantType","MANUAL"); mapper.insertAssignment(p); mapper.insertHistory("user_role_assignment",text(p,"userId"),null,p,by,text(p,"changeReason")); return mapper.assignments(Map.of("userId",text(p,"userId"),"roleCode",text(p,"roleCode"))).get(0); }
  @Transactional public Map<String,Object> updateAssignment(long id, Map<String,Object> p,String by){ requireReason(p); p.put("assignmentId",id); if(mapper.updateAssignment(p)==0) throw new AppException(HttpStatus.BAD_REQUEST,"INVALID_STATE","회수된 역할은 변경할 수 없습니다."); mapper.insertHistory("user_role_assignment",String.valueOf(id),null,p,by,text(p,"changeReason")); return mapper.assignments(Map.of()).stream().filter(r -> String.valueOf(r.get("assignmentId")).equals(String.valueOf(id))).findFirst().orElseThrow(); }
  @Transactional public Map<String,Object> revokeAssignment(long id, Map<String,Object> p,String by){ requireReason(p); if(mapper.revokeAssignment(id)==0) throw new AppException(HttpStatus.BAD_REQUEST,"INVALID_STATE","이미 회수된 역할입니다."); mapper.insertHistory("user_role_assignment",String.valueOf(id),null,Map.of("status","REVOKED"),by,text(p,"changeReason")); return mapper.assignments(Map.of()).stream().filter(r -> String.valueOf(r.get("assignmentId")).equals(String.valueOf(id))).findFirst().orElseThrow(); }
  @Transactional public List<Map<String,Object>> savePermissions(Map<String,Object> p,String by){ requireReason(p); List<Map<String,Object>> rows=(List<Map<String,Object>>)p.get("permissions"); if(text(p,"targetType")==null||text(p,"targetId")==null||rows==null) throw new AppException(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR","대상과 권한 목록은 필수입니다."); for(Map<String,Object> row: rows){ row.put("targetType",text(p,"targetType")); row.put("targetId",text(p,"targetId")); if(mapper.updatePermission(row)==0) mapper.insertPermission(row);} mapper.insertHistory("menu_permission",text(p,"targetType")+":"+text(p,"targetId"),null,p,by,text(p,"changeReason")); return mapper.permissions(Map.of("targetType",text(p,"targetType"),"targetId",text(p,"targetId"))); }
  @Transactional public List<Map<String,Object>> reorderMenus(Map<String,Object> p,String by){ requireReason(p); List<?> ids=(List<?>)p.get("orderedMenuIds"); if(ids==null||ids.isEmpty()) throw new AppException(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR","orderedMenuIds는 필수입니다."); int i=1; for(Object id:ids) mapper.updateMenuOrder(String.valueOf(id), i++); mapper.insertHistory("menu",String.valueOf(p.get("parentMenuId")),null,p,by,text(p,"changeReason")); return mapper.menus(Map.of()); }
  @Transactional public Map<String,Object> createMenu(Map<String,Object> p,String by){ requireReason(p); if(text(p,"menuName")==null||text(p,"url")==null) throw new AppException(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR","menuName과 url은 필수입니다."); p.putIfAbsent("menuId", UUID.randomUUID().toString()); p.putIfAbsent("menuLevel",3); defaultUse(p); mapper.insertMenu(p); mapper.insertHistory("menu",text(p,"menuId"),null,p,by,text(p,"changeReason")); return mapper.menus(Map.of("menuName",text(p,"menuName"))).get(0); }
  @Transactional public Map<String,Object> updateMenu(String id,Map<String,Object> p,String by){ requireReason(p); p.put("menuId",id); p.putIfAbsent("menuLevel",3); defaultUse(p); mapper.updateMenu(p); mapper.insertHistory("menu",id,null,p,by,text(p,"changeReason")); return mapper.menus(Map.of("menuName",text(p,"menuName"))).get(0); }
  @Transactional public Map<String,Object> createCodeGroup(String groupId,Map<String,Object> p,String by){ requireReason(p); p.put("groupId",groupId); defaultUse(p); mapper.insertCodeGroup(p); mapper.insertHistory("code_group",groupId,null,p,by,text(p,"changeReason")); return mapper.codeGroups(Map.of("groupId",groupId)).get(0); }
  @Transactional public Map<String,Object> updateCodeGroup(String groupId,Map<String,Object> p,String by){ requireReason(p); p.put("groupId",groupId); defaultUse(p); mapper.updateCodeGroup(p); mapper.insertHistory("code_group",groupId,null,p,by,text(p,"changeReason")); return mapper.codeGroups(Map.of("groupId",groupId)).get(0); }
  @Transactional public Map<String,Object> createCode(String groupId,String code,Map<String,Object> p,String by){ requireReason(p); p.put("groupId",groupId); p.put("codeValue",code); p.put("additionalAttributesJson",Jsons.toJson(p.getOrDefault("additionalAttributes",Map.of()))); defaultUse(p); mapper.insertCode(p); mapper.insertHistory("common_code",groupId+":"+code,null,p,by,text(p,"changeReason")); return mapper.codes(Map.of("groupId",groupId,"codeValue",code)).get(0); }
  @Transactional public Map<String,Object> updateCode(String groupId,String code,Map<String,Object> p,String by){ requireReason(p); p.put("groupId",groupId); p.put("codeValue",code); p.put("additionalAttributesJson",Jsons.toJson(p.getOrDefault("additionalAttributes",Map.of()))); defaultUse(p); mapper.updateCode(p); mapper.insertHistory("common_code",groupId+":"+code,null,p,by,text(p,"changeReason")); return mapper.codes(Map.of("groupId",groupId,"codeValue",code)).get(0); }
}
