package kr.ac.knue.common.admin;
import java.util.*;

public class SqlProvider {
  static boolean has(Map<String,Object> p, String k) { Object v=p.get(k); return v!=null && !String.valueOf(v).isBlank(); }
  static void like(StringBuilder s, Map<String,Object> p, String k, String col) { if (has(p,k)) s.append(" and ").append(col).append(" ilike concat('%', #{").append(k).append("}, '%')"); }
  static void eq(StringBuilder s, Map<String,Object> p, String k, String col) { if (has(p,k)) s.append(" and ").append(col).append("=#{").append(k).append("}"); }
  public String users(Map<String,Object> p){ StringBuilder s=new StringBuilder("select u.user_id as \"userId\", u.person_id as \"personId\", k.person_name as \"personName\", o.organization_name as \"organizationName\", k.job_grade as \"jobGrade\", k.employment_status as \"employmentStatus\", k.position_name as \"positionName\", k.retired_at as \"retiredAt\", k.last_synced_at as \"lastSyncedAt\", u.system_use_yn as \"systemUseYn\", u.status, coalesce(array_agg(a.role_code order by a.role_code) filter (where a.status='ACTIVE'), '{}') as \"roleCodes\" from user_account u join korus_person_snapshot k on k.person_id=u.person_id join organization o on o.organization_code=k.organization_code left join user_role_assignment a on a.user_id=u.user_id where 1=1"); like(s,p,"employeeNo","u.user_id"); like(s,p,"name","k.person_name"); like(s,p,"organization","o.organization_name"); eq(s,p,"jobGrade","k.job_grade"); eq(s,p,"employmentStatus","k.employment_status"); eq(s,p,"systemUseYn","u.system_use_yn"); if(has(p,"roleCode")) s.append(" and exists (select 1 from user_role_assignment ar where ar.user_id=u.user_id and ar.role_code=#{roleCode} and ar.status='ACTIVE')"); return s.append(" group by u.user_id,k.person_id,o.organization_name order by k.person_name asc limit 200").toString(); }
  public String organizations(Map<String,Object> p){ StringBuilder s=new StringBuilder("select o.organization_code as \"organizationCode\", o.organization_name as \"organizationName\", o.organization_type as \"organizationType\", (select rr.parent_organization_code from organization_relation_history rr where rr.organization_code=o.organization_code order by rr.effective_start_date desc limit 1) as \"parentOrganizationCode\", (select rr.effective_start_date from organization_relation_history rr where rr.organization_code=o.organization_code order by rr.effective_start_date desc limit 1) as \"effectiveStartDate\", (select rr.effective_end_date from organization_relation_history rr where rr.organization_code=o.organization_code order by rr.effective_start_date desc limit 1) as \"effectiveEndDate\", o.use_yn as \"useYn\" from organization o where 1=1"); like(s,p,"organizationCode","o.organization_code"); like(s,p,"organizationName","o.organization_name"); eq(s,p,"organizationType","o.organization_type"); return s.append(" order by o.organization_code limit 200").toString(); }
  public String roles(Map<String,Object> p){ StringBuilder s=new StringBuilder("select role_code as \"roleCode\", role_name as \"roleName\", purpose, grant_criteria as \"grantCriteria\", default_data_scope as \"defaultDataScope\", use_yn as \"useYn\" from role where 1=1"); eq(s,p,"roleCode","role_code"); like(s,p,"roleName","role_name"); eq(s,p,"useYn","use_yn"); return s.append(" order by role_code").toString(); }
  public String assignments(Map<String,Object> p){ StringBuilder s=new StringBuilder("select assignment_id as \"assignmentId\", user_id as \"userId\", role_code as \"roleCode\", grant_type as \"grantType\", approver_user_id as \"approverUserId\", valid_from as \"validFrom\", valid_to as \"validTo\", status from user_role_assignment where 1=1"); like(s,p,"userId","user_id"); eq(s,p,"roleCode","role_code"); eq(s,p,"grantType","grant_type"); eq(s,p,"status","status"); return s.append(" order by user_id, valid_from desc limit 200").toString(); }
  public String permissions(Map<String,Object> p){ StringBuilder s=new StringBuilder("select permission_id as \"permissionId\", target_type as \"targetType\", target_id as \"targetId\", menu_id as \"menuId\", access_yn as \"accessYn\" from menu_permission where 1=1"); eq(s,p,"targetType","target_type"); eq(s,p,"targetId","target_id"); eq(s,p,"menuId","menu_id"); return s.append(" order by target_type,target_id,menu_id limit 500").toString(); }
  public String menus(Map<String,Object> p){ StringBuilder s=new StringBuilder("select menu_id as \"menuId\", parent_menu_id as \"parentMenuId\", menu_level as \"menuLevel\", menu_name as \"menuName\", screen_id as \"screenId\", url, icon, business_category as \"businessCategory\", description, display_order as \"displayOrder\", use_yn as \"useYn\" from menu where 1=1"); like(s,p,"menuName","menu_name"); like(s,p,"screenId","screen_id"); like(s,p,"url","url"); like(s,p,"businessCategory","business_category"); eq(s,p,"useYn","use_yn"); return s.append(" order by coalesce(parent_menu_id,''), display_order limit 300").toString(); }
  public String codeGroups(Map<String,Object> p){ StringBuilder s=new StringBuilder("select group_id as \"groupId\", group_name as \"groupName\", description, managing_department as \"managingDepartment\", use_yn as \"useYn\" from code_group where 1=1"); like(s,p,"groupId","group_id"); like(s,p,"groupName","group_name"); like(s,p,"managingDepartment","managing_department"); eq(s,p,"useYn","use_yn"); return s.append(" order by group_id limit 200").toString(); }
  public String codes(Map<String,Object> p){ StringBuilder s=new StringBuilder("select group_id as \"groupId\", code_value as \"codeValue\", code_name as \"codeName\", parent_code_value as \"parentCodeValue\", sort_order as \"sortOrder\", additional_attributes as \"additionalAttributes\", valid_from as \"validFrom\", valid_to as \"validTo\", use_yn as \"useYn\" from common_code where group_id=#{groupId}"); like(s,p,"codeValue","code_value"); like(s,p,"codeName","code_name"); eq(s,p,"parentCodeValue","parent_code_value"); eq(s,p,"useYn","use_yn"); return s.append(" order by sort_order, code_value").toString(); }
  public String insertRole(Map<String,Object> p){ return "insert into role(role_code,role_name,purpose,grant_criteria,default_data_scope,use_yn) values(#{roleCode},#{roleName},#{purpose},#{grantCriteria},#{defaultDataScope},#{useYn})"; }
  public String updateRole(Map<String,Object> p){ return "update role set role_name=#{roleName}, purpose=#{purpose}, grant_criteria=#{grantCriteria}, default_data_scope=#{defaultDataScope}, use_yn=#{useYn}, updated_at=now() where role_code=#{roleCode}"; }
  public String insertOrgRelation(Map<String,Object> p){ return "insert into organization_relation_history(organization_code,parent_organization_code,effective_start_date,effective_end_date,change_reason) values(#{organizationCode},#{parentOrganizationCode},cast(#{effectiveStartDate} as date),cast(#{effectiveEndDate} as date),#{changeReason})"; }
  public String insertMenu(Map<String,Object> p){ return "insert into menu(menu_id,parent_menu_id,menu_level,menu_name,screen_id,url,icon,business_category,description,display_order,use_yn) values(#{menuId},#{parentMenuId},#{menuLevel},#{menuName},#{screenId},#{url},#{icon},#{businessCategory},#{description},#{displayOrder},#{useYn})"; }
  public String updateMenu(Map<String,Object> p){ return "update menu set parent_menu_id=#{parentMenuId}, menu_level=#{menuLevel}, menu_name=#{menuName}, screen_id=#{screenId}, url=#{url}, icon=#{icon}, business_category=#{businessCategory}, description=#{description}, display_order=#{displayOrder}, use_yn=#{useYn}, updated_at=now() where menu_id=#{menuId}"; }
  public String insertCodeGroup(Map<String,Object> p){ return "insert into code_group(group_id,group_name,description,managing_department,use_yn) values(#{groupId},#{groupName},#{description},#{managingDepartment},#{useYn})"; }
  public String updateCodeGroup(Map<String,Object> p){ return "update code_group set group_name=#{groupName}, description=#{description}, managing_department=#{managingDepartment}, use_yn=#{useYn}, updated_at=now() where group_id=#{groupId}"; }
  public String insertCode(Map<String,Object> p){ return "insert into common_code(group_id,code_value,code_name,parent_code_value,sort_order,additional_attributes,valid_from,valid_to,use_yn) values(#{groupId},#{codeValue},#{codeName},#{parentCodeValue},#{sortOrder},cast(#{additionalAttributesJson} as jsonb),cast(#{validFrom} as date),cast(#{validTo} as date),#{useYn})"; }
  public String updateCode(Map<String,Object> p){ return "update common_code set code_name=#{codeName}, parent_code_value=#{parentCodeValue}, sort_order=#{sortOrder}, additional_attributes=cast(#{additionalAttributesJson} as jsonb), valid_from=cast(#{validFrom} as date), valid_to=cast(#{validTo} as date), use_yn=#{useYn}, updated_at=now() where group_id=#{groupId} and code_value=#{codeValue}"; }
}
